apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
      role: web
  template:
    metadata:
      labels:
        app: frontend
        role: web
    spec:
      imagePullSecrets:
      - name: gitlab-registry
      containers:
      - image: registry.openculinary.org/reciperadar/frontend
        imagePullPolicy: IfNotPresent
        name: frontend
        ports:
        - containerPort: 80
  replicas: 3
